#!/usr/bin/env python3
"""
DJ Rara - Spotify Recommendation Engine
Main entry point for the application
"""

import sys
import argparse
from datetime import datetime
from spotify_auth import SpotifyAuthenticator
from recommendation_engine import SpotifyRecommendationEngine


def main():
    """Main entry point for the Spotify Recommendation Engine"""

    parser = argparse.ArgumentParser(
        description='DJ Rara - Spotify Recommendation Engine',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py --recommendations 50 --playlist-name "My Recommendations"
  python main.py -n 100 -p "Discover Weekly Alternative"
  python main.py --recommendations 30 --public
        """
    )

    parser.add_argument(
        '-n', '--recommendations',
        type=int,
        default=50,
        help='Number of recommendations to generate (default: 50)'
    )

    parser.add_argument(
        '-p', '--playlist-name',
        type=str,
        default=None,
        help='Name for the created playlist (default: "DJ Rara Recommendations - DATE")'
    )

    parser.add_argument(
        '--public',
        action='store_true',
        help='Make the playlist public (default: private)'
    )

    parser.add_argument(
        '--no-followed-artists',
        action='store_true',
        help='Don\'t use followed artists for recommendations'
    )

    parser.add_argument(
        '--no-top-artists',
        action='store_true',
        help='Don\'t use top artists for recommendations'
    )

    parser.add_argument(
        '--no-top-tracks',
        action='store_true',
        help='Don\'t use top tracks for recommendations'
    )

    parser.add_argument(
        '--display',
        type=int,
        default=20,
        help='Number of recommendations to display in console (default: 20)'
    )

    parser.add_argument(
        '--no-playlist',
        action='store_true',
        help='Skip creating a playlist, only display recommendations'
    )

    args = parser.parse_args()

    # Validate arguments
    if args.recommendations < 1:
        print("Error: Number of recommendations must be at least 1")
        sys.exit(1)

    if args.no_followed_artists and args.no_top_artists and args.no_top_tracks:
        print("Error: At least one recommendation source must be enabled")
        sys.exit(1)

    try:
        # Authenticate with Spotify
        print("=" * 60)
        print("DJ Rara - Spotify Recommendation Engine")
        print("=" * 60)
        print("\nAuthenticating with Spotify...")

        authenticator = SpotifyAuthenticator()
        sp = authenticator.authenticate()

        print("✓ Successfully authenticated!")

        # Get user info
        user = sp.current_user()
        print(f"\nWelcome, {user['display_name']}!")
        print(f"User ID: {user['id']}")

        # Initialize recommendation engine
        engine = SpotifyRecommendationEngine(sp)

        # Generate recommendations
        recommendations = engine.generate_personalized_recommendations(
            num_recommendations=args.recommendations,
            use_top_tracks=not args.no_top_tracks,
            use_top_artists=not args.no_top_artists,
            use_followed_artists=not args.no_followed_artists
        )

        if not recommendations:
            print("\n⚠ No recommendations found. Try adjusting your settings or listening to more music on Spotify.")
            sys.exit(0)

        # Display recommendations
        engine.display_recommendations(recommendations, max_display=args.display)

        # Create playlist if requested
        if not args.no_playlist:
            playlist_name = args.playlist_name or f"DJ Rara Recommendations - {datetime.now().strftime('%Y-%m-%d')}"

            description = (
                f"Personalized recommendations generated by DJ Rara on {datetime.now().strftime('%Y-%m-%d %H:%M')}. "
                f"Based on your listening habits including "
            )

            sources = []
            if not args.no_followed_artists:
                sources.append("followed artists")
            if not args.no_top_artists:
                sources.append("top artists")
            if not args.no_top_tracks:
                sources.append("top tracks")

            description += ", ".join(sources) + "."

            playlist = engine.create_playlist(
                playlist_name=playlist_name,
                tracks=recommendations,
                description=description,
                public=args.public
            )

            print(f"\n{'=' * 60}")
            print("🎉 Success!")
            print(f"{'=' * 60}")
            print(f"\nPlaylist '{playlist_name}' created successfully!")
            print(f"Listen now: {playlist['external_urls']['spotify']}")
        else:
            print(f"\n{'=' * 60}")
            print("✓ Recommendations generated successfully!")
            print(f"{'=' * 60}")

    except ValueError as e:
        print(f"\n❌ Configuration Error: {e}")
        print("\nPlease ensure you have:")
        print("1. Created a .env file (copy from .env.example)")
        print("2. Set your SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET")
        print("3. Registered your app at https://developer.spotify.com/dashboard")
        sys.exit(1)

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
